version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "ollama serve & sleep 5 && ollama run llama3.2 && tail -f /dev/null"

  postgres:
    image: pgvector/pgvector:pg13
    container_name: pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: eduardodandolini/spring-ai-chatbot:latest
    container_name: spring-ai-chatbot
    depends_on:
      - postgres
      - ollama
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      OLLAMA_HOST: http://ollama:11434
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  ollama_data:
  pgvector_data:
