version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "ollama serve & sleep 5 && ollama run mistral && tail -f /dev/null"

  postgres:
    image: postgis/postgis:13-3.1
    container_name: pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: >
      sh -c "psql -U user -d ai_db -c 'CREATE EXTENSION IF NOT EXISTS vector;' && postgres"

volumes:
  ollama_data:
  pgvector_data:
